name: PHP CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Installing dependencies
        uses: php-actions/composer@v6

      - name: Running tests
        uses: php-actions/phpunit@v3
        with:
          version: '9.6.11' 
          php_extensions: gd sqlite3 dom json libxml mbstring tokenizer xml xmlwriter zip
          args: --coverage-text

      - name: Tests completed
        run: echo "Job status is '${{ job.status }}'"





        
