name: PHP CI
run-name: ${{ github.repository }} CI PHPUnit

on:
  push:
    branches:
      - main

env:
  XDEBUG_MODE: coverage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Installing dependencies
        uses: php-actions/composer@v6

      - name: Running tests
        uses: php-actions/phpunit@v3
        continue-on-error: true
        with:
          version: '9.6.11' 
          php_extensions: gd sqlite3 dom json libxml mbstring tokenizer xml xmlwriter zip xdebug
          configuration: phpunit.xml

      - name: Uploading coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: always()
        with:
          filename: log/cobertura.xml
          badge: true
          format: markdown
          output: both

      - name: Tests completed
        run: echo "Job status is '${{ job.status }}'"

      - name: Exporting coverage to action summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
